import os

SQL_ALCHEMY_DATABSE_URI = os.environ.get("DATABASE_URL")
SQLALCHEMY_TRACK_MODIFICAATIONS = False

ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD")
ADMIN_USERNAME = os.environ.get("ADMIN_USERNAME")
